media:
  input: _uploads
  output: /uploads
content:
  - name: aanmelden
    label: Aanmelden
    type: file
    path: aanmelden.markdown
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: photos
        label: Photos
        type: object
        list: true
        fields:
          - name: image
            label: Photo
            type: image
          - name: txt
            label: Alt text
            type: string
      - name: layout
        label: Layout
        type: string
        default: page
        hidden: true
  - name: artikel
    label: Nieuws
    type: collection
    path: _posts
    filename: '{year}-{month}-{day}-{primary}.markdown'
    view:
      fields: [ date, title ]
      primary: title
      sort: [ date, title ]
      default:
        search: ''
        sort: date
        order: desc
    fields:
      - name: date
        label: Date
        type: date
        options:
          time: true
          format: yyyy-MM-dd HH:mm:ss xxx
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: photos
        label: Photos
        type: object
        list: true
        fields:
          - name: image
            label: Photo
            type: image
          - name: txt
            label: Alt text
            type: string
  - name: winnaar
    label: Winnaars
    type: collection
    path: _winners
    filename: '{primary}.markdown'
    view:
      fields: [ title, year ]
      primary: title
      sort: [ year ]
      default:
        search: ''
        sort: year
        order: desc
    fields:
      - name: year
        label: Year
        type: number
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: photos
        label: Photos
        type: object
        list: true
        fields:
          - name: image
            label: Photo
            type: image
          - name: txt
            label: Alt text
            type: string
    
    
    
  