media:
  input: _uploads
  output: /uploads
content:
  - name: _posts
    label: Nieuws
    type: collection
    path: _posts
    view:
      fields: [ title ]
      primary: title
      sort: [ date, title ]
      default:
        search: ''
        sort: date
        order: desc
    fields:
      - name: date
        label: Date
        type: date
        options:
          time: true
          format: yyyy-MM-dd HH:mm:ss xxx
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text