---
title: Philip Bloemendal Prijs
timezone: Europe/Amsterdam
collections:
  winners:
    title: Winnaars
    output: true
    permalink: "/winnaar/:title"
  posts:
    title: Nieuws
    output: true
    permalink: "/artikel/:title"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    background_image: "/assets/img/header-bg-pb.jpg"
    photos:
    - image: 
      txt:
    videos: []
email: bloemendalprijs@beeldengeluid.nl
description: >- # this means to ignore newlines until "baseurl:"
  De Phillip Bloemendal Prijs stimuleert jong journalistiek presentatietalent in de media. Genomineerden ontvangen een oorkonde en de winnaar ontvangt tevens een geldbedrag van 3500 euro, te besteden aan een studie- of opleidingsproject om zich binnen het vakgebied verder te bekwamen.
baseurl: "/bloemendal" # the subpath of your site, e.g. /blog
# url: "https://beeldengeluid.github.io" # the base hostname & protocol for your site, e.g. http://example.com
url: ""
twitter_username: bloemendalprijs

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
