---
title: Philip Bloemendal Prijs
timezone: Europe/Amsterdam
collections:
  posts:
    title: Nieuws
    output: true
    permalink: "/artikel/:title"
  uploads:
    title: Uploads
    output: true
  winners:
    title: Winnaars
    output: true
    permalink: "/winnaar/:title"
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    background_image: "/assets/img/header-bg-pb.jpg"
    photos:
    - image: 
      txt: 
    videos: []
- scope:
    path: ''
    type: posts
  values:
    layout: page
    background_image: "/assets/img/header-bg-news.jpg"
    photos:
    - image: 
      txt: 
    videos: []
- scope:
    path: ''
    type: winners
  values:
    layout: page
    year: 
    background_image: "/assets/img/header-bg-winners.jpg"
    photos:
    - image: 
      txt: 
    videos: []
email: bloemendalprijs@beeldengeluid.nl
description: De Philip Bloemendal Prijs stimuleert jong journalistiek presentatietalent
  in de media. Genomineerden ontvangen een oorkonde en de winnaar ontvangt tevens
  een geldbedrag van 3500 euro, te besteden aan een studie- of opleidingsproject om
  zich binnen het vakgebied verder te bekwamen.
baseurl: 
url: https://www.bloemendal.info
twitter_username: bloemendalprijs
markdown: kramdown
plugins:
- jekyll-feed
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- script
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
